[pytest]
testpaths = tests
addopts = --basetemp=tmp/pytest
cache_dir = tmp/pytest-cache
filterwarnings =
    ignore:Using `httpx` with `starlette.testclient` is deprecated:starlette.exceptions.StarletteDeprecationWarning
    ignore:The default value of `allowed_objects` will change:langchain_core._api.deprecation.LangChainPendingDeprecationWarning
    ignore:'asyncio.iscoroutinefunction' is deprecated and slated for removal in Python 3.16:DeprecationWarning
